### ISSUE TITLE
How to make it work in docker?

### ISSUE THREAD

**Issue by ozbillwang** [ndelitski/ssh2ec2#2]
`ssh2ec2` looks useful and I'd like to run it as local command within docker container.

```
alias ssh2ec2="docker run -ti --rm <account>/ssh2ec2 "
ssh2ec2 stack
```

I build it in alpine node-npm image:

```
$ cat Dockerfile
FROM jkilbride/node-npm-alpine:6

RUN apk --update add git bash
RUN git clone https://github.com/ndelitski/ssh2ec2.git
RUN cd ssh2ec2 & npm -g i ssh2ec2

ENTRYPOINT ["ssh2ec2"]
CMD ["-help"]
```

But when I run the container, got this error:

```
$ docker build -t ssh2ec2 . 
$ docker run -ti --rm ssh2ec2 stack
module.js:457 throw err; ^ Error: Cannot find module '/usr/lib/node_modules/ssh2ec2/dist/command.js' at Function.Module._resolveFilename (module.js:455:15) at Function.Module._load (module.js:403:25) at Module.runMain (module.js:590:10) at run (bootstrap_node.js:394:7) at startup (bootstrap_node.js:149:9) at bootstrap_node.js:509:3
/usr/bin/ssh2ec2: line 22: module.js:457: command not found
```

Any suggestions?

**Comment by ndelitski** [comment]
hi @SydOps 
try this

```
FROM jkilbride/node-npm-alpine:6

RUN apk --update add git bash
RUN npm -g i ssh2ec2

ENTRYPOINT ["ssh2ec2"]
```

Also program need to know where your ssh keys are stored, so add `SSH_KEYS_PATH` env to your `docker run` command. AWS credentials are picked from env variables or file in user home directory (in my case)

```
docker run -it --rm -v $HOME:/root -e SSH_KEYS_PATH=/root/keys ssh2ec2
```

**Comment by ozbillwang** [comment]
thanks, @ndelitski , the issue is gone. 

Where you read the aws api key/secret? from ~/.aws ? So I can mount it as well:

```
docker run -it --rm -v $HOME/.ssh:/root/.ssh:ro -v $HOME/.aws:/root/.aws:ro -e SSH_KEYS_PATH=/root/.ssh ssh2ec2 stack
```

But always get `no instances found with name 'stack'`, what name I need provider, for example I need list the instance with Tags:Name is lb01 or Tags:env is prod?

**Comment by ndelitski** [comment]
The command searches against `Tags:Name` and instance must have publicDNS and `state:running` in order to appear in a suggest list, try `ssh2ec2 lb`
